### ISSUE TITLE
[QUESTION] can we open a new telnet session via SSH 

### ISSUE THREAD

**Issue by admcilgin** [YowFung/telnet#2]
Hi thanks for your awesome package, I want to ask you about a use case, 
Can I create TLS connection via ssh session ? did you try this or do you have to plan work on it ?

**Comment by YowFung** [comment]
@admcilgin 
I didn't understand your need. You can create TLS connection with `TelnetClient.startSecureConnect(...)` but it's also a telnet session. Why ssh connection?
You can reference the following packages if you want to create an ssh connection:
- [ssh](https://pub.dev/packages/ssh)
- [ssh2](https://pub.dev/packages/ssh2)
- [libssh](https://pub.dev/packages/libssh_binding)
- [dartssh](https://pub.dev/packages/dartssh)
- [dartssh2](https://pub.dev/packages/dartssh2)

**Comment by admcilgin** [comment]
i mean that , i wan to develop an app to connect the remote server's telnet port.
We have a remote server and it has a telnet port for debugging so i want to create an flutter app to connect this remote telnet port from another host so i need to make ssh connection first and tls connection over the the ssh connection

**Comment by YowFung** [comment]
In my opinion, the "telnet connection" you are referring to is just a client on the server to which you are connected via SSH, not the client of your Flutter application. You should focus on how your remote ssh service is implemented, rather than the Flutter application.

**Comment by admcilgin** [comment]
thanks
